name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make builder
      run: make builder
    - name: make testbuild
      run: make testbuild
    - name: run testbuild
      run: ./testbuild
