name: C/C++ CI

on:
  push:
    branches: [ add-workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: print diagnostics
      run: |
        pwd
        ls
      
    - name: make TestBuilder
      run: make TestBuilder
    - name: make pebble_textbuild.exe
      run: make pebble_testbuild.exe
    - name: run pebble_testbuild.exe
      run: ./pebble_testbuild.exe --ignore-custom
