name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make testbuilder
      run: make testbuilder
    - name: make pebble_testbuild
      run: make pebble_testbuild
    - name: run pebble_testbuild
      run: ./pebble_testbuild.exe --ignore-custom --bytecode
